version: "3.9"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: nnpda
      POSTGRES_USER: nnpdauser
      POSTGRES_PASSWORD: nnpdapassword
    ports:
      - "5432:5432"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
    ports:
      - "5044:5044"
      - "9200:9200"

  logstash:
    image: docker.elastic.co/logstash/logstash:8.10.2
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./postgresql-42.7.4.jar:/usr/share/logstash/postgresql-42.7.4.jar
    depends_on:
      - elasticsearch
      - db

  kibana:
    image: docker.elastic.co/kibana/kibana:8.10.2
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"